const { chromium } = require('playwright');
let fails = 0; const ok = (c, msg) => { if (!c) fails++; console.log((c ? 'ok   ' : 'FAIL ') + msg); };
(async () => {
  const b = await chromium.launch(require('./common').launchOptions);
  const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, timezoneId: 'America/Edmonton' });
  await ctx.addInitScript(() => { if(!localStorage.getItem('teachingtools:timeCounter:ui')) localStorage.setItem('teachingtools:timeCounter:ui', JSON.stringify({setupSeen: true})); });
  const p = await ctx.newPage(); const errs = []; p.on('pageerror', e => errs.push(String(e))); p.on('console', m => { if (m.type() === 'error') errs.push(m.text()); });
  await p.clock.install({ time: new Date('2026-10-08T10:00:00') });
  await p.goto(require('./common').URL); await p.waitForTimeout(250);
  await p.evaluate(() => TimeCounterApp.commit(m => { const TC = TimeCounter, v = m.versions[0];
    TC.missingDayTypeDates(m, 5).forEach((d, i) => TC.setDayType(m, d, ['friA','friB','friC','friD'][i % 4]));
    ['mon','tue','wed','thu'].forEach(dt => ['p1','p2','p3','p4','p6','p7'].forEach(id => TC.setTimetable(v, dt, id, {type: 'class', name: 'Math 8'}))); })); await p.waitForTimeout(200);
  const vis = sel => p.locator(sel).evaluateAll(els => els.filter(e => e.offsetParent !== null).length);
  ok(await vis('.wk-head') === 1 && await vis('.wk-body') === 1, 'on a phone the week shows one day');
  ok((await p.innerText('.wk-head.sel .d1')).includes('Oct 8'), 'it opens on today (Thu Oct 8)');
  ok(await vis('.daybar .chipbtn') === 5, 'with a button for each school day');
  const over = () => p.evaluate(() => document.documentElement.scrollWidth - window.innerWidth);
  ok(await over() <= 1, 'and no sideways scroll (' + await over() + ' px)');
  await p.tap('.daybar [data-act=day-next]'); await p.waitForTimeout(150);
  ok((await p.innerText('.wk-head.sel .d1')).includes('Oct 9'), 'next goes to Friday');
  await p.tap('.daybar [data-act=day-next]'); await p.waitForTimeout(250);
  ok((await p.innerText('.wkt')).startsWith('Mon Oct 12') && (await p.innerText('.wk-head.sel .d1')).includes('Oct 12'), 'next past Friday goes to Monday of the next week (Oct 12, Thanksgiving)');
  await p.tap('.daybar [data-act=day-prev]'); await p.waitForTimeout(250);
  ok((await p.innerText('.wkt')).startsWith('Mon Oct 5') && (await p.innerText('.wk-head.sel .d1')).includes('Oct 9'), 'previous from there goes back to Friday');
  await p.tap('.daybar [data-date="2026-10-05"]'); await p.waitForTimeout(200);
  ok((await p.innerText('.wk-head.sel .d1')).includes('Oct 5') && await vis('.wk-body') === 1, 'a day button shows that day');
  await p.tap('[data-act=wk-next]'); await p.waitForTimeout(250);
  ok((await p.innerText('.wk-head.sel .d1')).includes('Oct 12'), 'moving to another week keeps the weekday (Monday)');
  await p.tap('.daybar [data-date="2026-10-14"]'); await p.waitForTimeout(150);
  await p.locator('.wk-body.sel .blk').first().tap(); await p.waitForSelector('dialog[open]');
  ok((await p.innerText('dialog[open] h2')).includes('Edit block'), 'a tap on a block opens its form');
  await p.keyboard.press('Escape'); await p.waitForTimeout(150);
  await p.screenshot({ path: require('path').join(require('./common').out('phone'), 'phone-week.png') });
  // and a wide screen still shows the whole week
  await p.setViewportSize({ width: 1200, height: 900 }); await p.waitForTimeout(200);
  ok(await vis('.wk-head') >= 5 && await vis('.daybar') === 0, 'a wide screen still shows the whole week, without the day buttons');
  ok(errs.length === 0, 'no console errors ' + JSON.stringify(errs));
  await b.close(); console.log(fails ? fails + ' FAILED' : 'all passed'); process.exit(fails ? 1 : 0);
})();
